### ISSUE TITLE
error rquest

### ISSUE THREAD

**Issue by guer0125** [guer0125/fastness-fixer#1]
im getting an **avoid missing and error request - The page has 1 error response(s). with code 404.**  

not sure what that is?

@HannahDelaney

**Comment by HannahDelaney** [comment]
I just tried in Markbot, and I think that error has to do with a typo that needs to be fixed.

On line 49 of your most recent commit, (it is an `embed` container for the second image) the .jpg is called "snai1.jpg", and you'll need to change it to match the asset folder, so "snail.jpg".

It's hard to see it in the font Markbot uses.

**Comment by guer0125** [comment]
got it, thank you :)
